### ISSUE TITLE
Unittest on Github CI keeps failing

### ISSUE THREAD

**Issue by minchuncho** [minchuncho/sewup#3]
In the CI step `make test`, a segmentation fault always arises during "collecting items..." @yungyuc

**Comment by yungyuc** [comment]
Could you also provide the URL pointing to the GitHub Action CI run?  Preferably the link at the failed line in the log.

**Comment by minchuncho** [comment]
Sure, the link at the failed line is provided below:
https://github.com/minchuncho/sewup/runs/6451388536?check_suite_focus=true#step:5:11

Note that the actions after this one all have the same problem thus far. Thank you :))

**Comment by yungyuc** [comment]
The first step of troubleshooting a failure on CI is to reproduce it locally.  Since this crashes with Linux/Ubuntu, you will need a similar environment.  If you have not set up the environment, it might be worth a try.

Another issue is the multitude of compiler warnings like in https://github.com/minchuncho/sewup/runs/6466866719?check_suite_focus=true#step:4:7 .  Some of them look malign.  Do you seem them locally or do they only manifest on github action?

Again, it's important to check what is happening locally.

**Comment by minchuncho** [comment]
Oh I see, I indeed didn't try running it on a similar environment. I basically run on osx and when the program is all fine, I simply change the content of Makefile to accomodate the Github runner. Anyways, I will try it tmr, thank you!

And yes, those warnings did appear locally but I haven't fixed them as the program works well locally and the warnings are (mostly) related to the codes that I haven't tested. I will also look into those warnings and fix them asap.

Very appreciate your suggestions and time.

**Comment by yungyuc** [comment]
No problem!  Github Action also has mac runner (see [example setup](https://github.com/solvcon/modmesh/blob/7fc445eccc3838977b8c8ceb1a74beab802ea81e/.github/workflows/modmesh_pytest.yml#L41) and [example run](https://github.com/solvcon/modmesh/runs/6475903668?check_suite_focus=true)).  If you mainly develop on mac, switching to a mac runner might save your time.
